/**
 * ════════════════════════════════════════════════════════════════════════════
 * Box Truck Boss · Welcome Modal · welcomeModalAudioConfig.js
 * Generated by Calibration Studio v3
 * ════════════════════════════════════════════════════════════════════════════
 */

export const WELCOME_MODAL_MUSIC_TIMELINE = [
  { file: "music_predawn_yard.mp3", spansActs: ["1","2","3"], actVolumes: {"1":0.4,"2":0.4,"3":0.4}, fadeInMs: 1000, fadeOutMs: 800 },
  { file: "music_voicemail.mp3", spansActs: ["4"], actVolumes: {"4":0.4}, fadeInMs: 700, fadeOutMs: 800 },
  { file: "music_csa_score.mp3", spansActs: ["5"], actVolumes: {"5":0.5}, fadeInMs: 700, fadeOutMs: 900 },
  { file: "music_curriculum.mp3", spansActs: ["6","7"], actVolumes: {"6":0.35,"7":0.3}, fadeInMs: 700, fadeOutMs: 1000 },
  { file: "music_despair_to_hope.mp3", spansActs: ["8","8_5","9","10"], actVolumes: {"8":0.07,"9":0.5,"10":0.5,"8_5":0.25}, fadeInMs: 1000, fadeOutMs: 1000 },
  { file: "music_launch.mp3", spansActs: ["12"], actVolumes: {"12":0.45}, fadeInMs: 800, fadeOutMs: 800 },
];

export const ACT1_AUDIO_CUES = {
  vo: [
  ],
  sfx: [
  ],
};

export const ACT2_AUDIO_CUES = {
  vo: [
  ],
  sfx: [
  ],
};

export const ACT3_AUDIO_CUES = {
  vo: [
  ],
  sfx: [
    { startMs: -150, file: "sfx_phone_notification.mp3", volume: 0.75 },
  ],
};

export const ACT4_AUDIO_CUES = {
  vo: [
    { startMs: 800, endMs: 2400, file: "marcus_act4_01_hey_marcus.mp3", volume: 1 },
    { startMs: 2900, endMs: 5600, file: "marcus_act4_02_dispatching_23_years.mp3", volume: 1 },
    { startMs: 6000, endMs: 9700, file: "marcus_act4_03_rich_or_broke.mp3", volume: 1 },
    { startMs: 10200, endMs: 13850, file: "marcus_act4_04_first_ninety_days.mp3", volume: 1 },
    { startMs: 14200, endMs: 16000, file: "marcus_act4_05_log_in_tomorrow.mp3", volume: 1 },
    { startMs: 16000, endMs: 17950, file: "marcus_act4_06_pick_up_the_phone.mp3", volume: 1 },
    { startMs: 19300, endMs: 22700, file: "marcus_act4_07_prepare_yourself.mp3", volume: 1 },
  ],
  sfx: [
  ],
};

export const ACT5_AUDIO_CUES = {
  vo: [
    { startMs: 600, endMs: 3980, file: "marcus_act5_01_not_what_hurts.mp3", volume: 1 },
    { startMs: 4180, endMs: 7710, file: "marcus_act5_02_csa_score_takes_hit.mp3", volume: 1 },
    { startMs: 8110, endMs: 9870, file: "marcus_act5_03_insurance_premium.mp3", volume: 1 },
    { startMs: 10270, endMs: 12790, file: "marcus_act5_04_brokers_stop_calling.mp3", volume: 1 },
    { startMs: 13140, endMs: 16720, file: "marcus_act5_05_lose_your_MC.mp3", volume: 1 },
    { startMs: 17070, endMs: 20650, file: "marcus_act5_06_two_years.mp3", volume: 1 },
  ],
  sfx: [
    { startMs: 7400, file: "sfx_csa_stamp_01.mp3", volume: 0.65 },
    { startMs: 12500, file: "sfx_csa_stamp_02.mp3", volume: 0.65 },
    { startMs: 16400, file: "sfx_csa_stamp_03.mp3", volume: 0.65 },
    { startMs: 20400, file: "sfx_csa_stamp_730_days.mp3", volume: 0.8 },
  ],
};

export const ACT6_AUDIO_CUES = {
  vo: [
    { startMs: 400, endMs: 4050, file: "marcus_act6_01_catch_on_dipstick.mp3", volume: 1 },
    { startMs: 4800, endMs: 8450, file: "marcus_act6_02_react_in_the_moment.mp3", volume: 1 },
    { startMs: 9200, endMs: 12750, file: "marcus_act6_03_pass_DOT_inspections.mp3", volume: 1 },
    { startMs: 13600, endMs: 17100, file: "marcus_act6_04_back_into_the_dock.mp3", volume: 1 },
    { startMs: 18000, endMs: 21650, file: "marcus_act6_05_operate_the_liftgate.mp3", volume: 1 },
  ],
  sfx: [
  ],
};

export const ACT7_AUDIO_CUES = {
  vo: [
    { startMs: 400, endMs: 4650, file: "marcus_act7_01_negotiate_with_brokers.mp3", volume: 1 },
    { startMs: 5400, endMs: 9600, file: "marcus_act7_02_hire_right_drivers_KYP.mp3", volume: 1 },
    { startMs: 10400, endMs: 14600, file: "marcus_act7_03_strategic_about_every_truck.mp3", volume: 1 },
    { startMs: 15400, endMs: 18750, file: "marcus_act7_04_run_company_efficiently.mp3", volume: 1 },
  ],
  sfx: [
    { startMs: 0, synth: "decision_strike", params: {"variant":1}, volume: 0.7 },
    { startMs: 5000, synth: "decision_strike", params: {"variant":2}, volume: 0.75 },
    { startMs: 10000, synth: "decision_strike", params: {"variant":3}, volume: 0.8 },
    { startMs: 15000, synth: "decision_strike", params: {"variant":4}, volume: 0.85 },
  ],
};

export const ACT8_AUDIO_CUES = {
  vo: [
    { startMs: 600, endMs: 4550, file: "marcus_act8_01_truck_breaks_you_break.mp3", volume: 1 },
    { startMs: 5400, endMs: 6950, file: "marcus_act8_02_both.mp3", volume: 1 },
    { startMs: 10200, endMs: 14550, file: "marcus_act8_03_how_you_respond.mp3", volume: 1 },
  ],
  sfx: [
    { startMs: 0, endMs: 16000, file: "sfx_rain_ambience.mp3", volume: 0.6 },
  ],
};

export const ACT8_5_AUDIO_CUES = {
  vo: [
    { startMs: 200, endMs: 2250, file: "marcus_act8_5_01_not_for_the_weak.mp3", volume: 1 },
    { startMs: 2500, endMs: 4500, file: "marcus_act8_5_02_resilient_resourceful.mp3", volume: 1 },
    { startMs: 4600, endMs: 7750, file: "marcus_act8_5_03_in_your_corner.mp3", volume: 1 },
  ],
  sfx: [
  ],
};

export const ACT9_AUDIO_CUES = {
  vo: [
    { startMs: 1750, endMs: 3850, file: "marcus_act9_01_one_becomes_three.mp3", volume: 1 },
    { startMs: 7750, endMs: 10500, file: "marcus_act9_02_becomes_a_fleet.mp3", volume: 1 },
    { startMs: 10550, endMs: 15800, file: "marcus_act9_03_name_in_this_industry.mp3", volume: 1 },
  ],
  sfx: [
    { startMs: 500, file: "sfx_bay_door_rumble.mp3", volume: 0.45 },
    { startMs: 3750, file: "sfx_bay_door_rumble.mp3", volume: 0.45 },
    { startMs: 7200, file: "sfx_bay_door_rumble.mp3", volume: 0.45 },
    { startMs: 10200, file: "sfx_bay_door_rumble.mp3", volume: 0.45 },
    { startMs: 13300, file: "sfx_bay_door_rumble.mp3", volume: 0.45 },
  ],
};

export const ACT10_AUDIO_CUES = {
  vo: [
  ],
  sfx: [
    { startMs: 2000, synth: "xray_pulse", volume: 0.55 },
  ],
};

export const ACT11_AUDIO_CUES = {
  vo: [
    { startMs: 200, endMs: 2750, file: "marcus_act11_01_not_forgiving.mp3", volume: 1 },
    { startMs: 2900, endMs: 7550, file: "marcus_act11_02_life_savings_dozen_ways.mp3", volume: 1 },
    { startMs: 7800, endMs: 12000, file: "marcus_act11_03_face_all_of_them.mp3", volume: 1 },
  ],
  sfx: [
  ],
};

export const ACT12_AUDIO_CUES = {
  vo: [
    { startMs: 800, endMs: 2250, file: "marcus_act12_01_keys_are_yours.mp3", volume: 1 },
    { startMs: 2400, endMs: 3900, file: "marcus_act12_02_keep_it_safe.mp3", volume: 1 },
    { startMs: 4400, endMs: 5950, file: "marcus_act12_03_road_been_waiting.mp3", volume: 1 },
    { startMs: 6000, endMs: 10300, file: "marcus_act12_04_hustle_in_motion.mp3", volume: 1 },
  ],
  sfx: [
    { startMs: 6500, file: "sfx_truck_ignition.mp3", volume: 0.3 },
  ],
};

export const ACT_CUES_BY_KEY = {
  "1": ACT1_AUDIO_CUES,
  "2": ACT2_AUDIO_CUES,
  "3": ACT3_AUDIO_CUES,
  "4": ACT4_AUDIO_CUES,
  "5": ACT5_AUDIO_CUES,
  "6": ACT6_AUDIO_CUES,
  "7": ACT7_AUDIO_CUES,
  "8": ACT8_AUDIO_CUES,
  "8_5": ACT8_5_AUDIO_CUES,
  "9": ACT9_AUDIO_CUES,
  "10": ACT10_AUDIO_CUES,
  "11": ACT11_AUDIO_CUES,
  "12": ACT12_AUDIO_CUES,
};

// ─── ALL_AUDIO_MANIFEST: { category, file } objects required by AudioMixer.preload ───
export const ALL_AUDIO_MANIFEST = [
  { category: "marcus", file: "marcus_act11_01_not_forgiving.mp3" },
  { category: "marcus", file: "marcus_act11_02_life_savings_dozen_ways.mp3" },
  { category: "marcus", file: "marcus_act11_03_face_all_of_them.mp3" },
  { category: "marcus", file: "marcus_act12_01_keys_are_yours.mp3" },
  { category: "marcus", file: "marcus_act12_02_keep_it_safe.mp3" },
  { category: "marcus", file: "marcus_act12_03_road_been_waiting.mp3" },
  { category: "marcus", file: "marcus_act12_04_hustle_in_motion.mp3" },
  { category: "marcus", file: "marcus_act4_01_hey_marcus.mp3" },
  { category: "marcus", file: "marcus_act4_02_dispatching_23_years.mp3" },
  { category: "marcus", file: "marcus_act4_03_rich_or_broke.mp3" },
  { category: "marcus", file: "marcus_act4_04_first_ninety_days.mp3" },
  { category: "marcus", file: "marcus_act4_05_log_in_tomorrow.mp3" },
  { category: "marcus", file: "marcus_act4_06_pick_up_the_phone.mp3" },
  { category: "marcus", file: "marcus_act4_07_prepare_yourself.mp3" },
  { category: "marcus", file: "marcus_act5_01_not_what_hurts.mp3" },
  { category: "marcus", file: "marcus_act5_02_csa_score_takes_hit.mp3" },
  { category: "marcus", file: "marcus_act5_03_insurance_premium.mp3" },
  { category: "marcus", file: "marcus_act5_04_brokers_stop_calling.mp3" },
  { category: "marcus", file: "marcus_act5_05_lose_your_MC.mp3" },
  { category: "marcus", file: "marcus_act5_06_two_years.mp3" },
  { category: "marcus", file: "marcus_act6_01_catch_on_dipstick.mp3" },
  { category: "marcus", file: "marcus_act6_02_react_in_the_moment.mp3" },
  { category: "marcus", file: "marcus_act6_03_pass_DOT_inspections.mp3" },
  { category: "marcus", file: "marcus_act6_04_back_into_the_dock.mp3" },
  { category: "marcus", file: "marcus_act6_05_operate_the_liftgate.mp3" },
  { category: "marcus", file: "marcus_act7_01_negotiate_with_brokers.mp3" },
  { category: "marcus", file: "marcus_act7_02_hire_right_drivers_KYP.mp3" },
  { category: "marcus", file: "marcus_act7_03_strategic_about_every_truck.mp3" },
  { category: "marcus", file: "marcus_act7_04_run_company_efficiently.mp3" },
  { category: "marcus", file: "marcus_act8_01_truck_breaks_you_break.mp3" },
  { category: "marcus", file: "marcus_act8_02_both.mp3" },
  { category: "marcus", file: "marcus_act8_03_how_you_respond.mp3" },
  { category: "marcus", file: "marcus_act8_5_01_not_for_the_weak.mp3" },
  { category: "marcus", file: "marcus_act8_5_02_resilient_resourceful.mp3" },
  { category: "marcus", file: "marcus_act8_5_03_in_your_corner.mp3" },
  { category: "marcus", file: "marcus_act9_01_one_becomes_three.mp3" },
  { category: "marcus", file: "marcus_act9_02_becomes_a_fleet.mp3" },
  { category: "marcus", file: "marcus_act9_03_name_in_this_industry.mp3" },
  { category: "music", file: "music_csa_score.mp3" },
  { category: "music", file: "music_curriculum.mp3" },
  { category: "music", file: "music_despair_to_hope.mp3" },
  { category: "music", file: "music_launch.mp3" },
  { category: "music", file: "music_predawn_yard.mp3" },
  { category: "music", file: "music_voicemail.mp3" },
  { category: "sfx", file: "sfx_bay_door_rumble.mp3" },
  { category: "sfx", file: "sfx_csa_stamp_01.mp3" },
  { category: "sfx", file: "sfx_csa_stamp_02.mp3" },
  { category: "sfx", file: "sfx_csa_stamp_03.mp3" },
  { category: "sfx", file: "sfx_csa_stamp_730_days.mp3" },
  { category: "sfx", file: "sfx_phone_notification.mp3" },
  { category: "sfx", file: "sfx_rain_ambience.mp3" },
  { category: "sfx", file: "sfx_truck_ignition.mp3" },
];
